"use client";

import { useTranslation } from 'react-i18next';
import { YellowBackgroundTop } from "./BG/YellowBackgroundTop";
import { JSXElementConstructor, Key, ReactElement, ReactNode, ReactPortal, useEffect, useRef, useState } from "react";

export function Industries() {
  const { t, i18n } = useTranslation('designtech');
  const containerRef = useRef<HTMLElement>(null);
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const [isMobile, setIsMobile] = useState(false);

  // Check for mobile viewport
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768); // 768px is the md breakpoint
    };

    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const toggleAccordion = (index: number) => {
    if (!isMobile) {
      setOpenIndex(openIndex === index ? null : index);
    }
  };

  // Branchen-Daten je nach Sprache
  const getIndustries = () => {
    if (i18n.language === 'en') {
      return {
        "Drive Technology": [
          "Drive Systems",
          "Electric Drives",
          "Plain Bearing Technology",
          "Industrial Drives",
          "Linear Technology",
          "Machine Bearings",
          "Servo Technology",
        ],
        "Wood Industry": [
          "Forestry Technology",
          "Woodworking Machines",
          "Splitting Technology",
          "Sawmill",
        ],
        "Medical Technology": [
          "Ventilation Technology",
          "Medical Equipment Technology",
          "Medical Instruments",
          "Medical Measuring Devices",
          "Dental Technology",
        ],
        "Automation Technology": [
          "Automated Machines",
          "Automation Equipment",
          "Automation",
          "Automation Components",
          "Machine Controls",
          "Positioning Systems",
          "Production Automation",
          "Control Unit",
          "Control System",
          "Control Technology",
        ],
        "Plant Engineering": [
          "Plant Engineering Components",
          "Plant Technology",
          "Manufacturing Plant",
          "Industrial Extraction Systems",
          "Industrial Plant Technology",
        ],
        "Measurement Technology": [
          "Analog Measurement Technology",
          "Pressure Measurement Technology",
          "Electrical Measurement Technology",
          "Industrial Measurement Technology",
          "Infrared Measurement Technology",
          "Laser Measurement Technology",
          "Measuring Systems",
          "Measuring Devices",
          "Measuring Machines",
          "Micro Measurement Technology",
          "Sensor Measurement Technology",
        ],
        "Printing Technology": [
          "3D Printing",
          "Digital Printing",
          "Printing Systems",
          "Offset Printing",
          "Screen Printing",
          "Pad Printing",
          "Textile Printing",
          "Thermal Printing",
          "Gravure Printing",
          "Transfer Printing",
        ],
        "Industrial Robots": [
          "Work Robots",
          "Assembly Robots",
          "Handling Robots",
          "Painting Robots",
          "Linear Robots",
          "Manipulation Robots",
          "Nano Robots",
          "Portal Robots",
          "Precision Robots",
          "Robots",
          "Robot Systems",
          "Robot Systems",
          "Robot Technology",
          "Heavy Load Robots",
          "Six-Axis Robots",
        ],
        "Surface Technology": [
          "Coating Systems",
          "Coating Equipment",
          "Coating Machines",
          "Painting Systems",
          "Painting Equipment",
          "Painting Machines",
          "Surface Treatment Systems",
          "Surface Cleaning",
          "Polishing Systems",
          "Polishing Machines",
          "Powder Coatings",
        ],
        "Electrical Engineering": [
          "Display Units",
          "Electrical Equipment",
          "Industrial Electronics",
          "Electrical Outlet",
          "Plug",
          "Connector",
          "Transformers",
        ],
        "Information Technology": [
          "Digital Media",
          "Information Electronics",
          "Information Systems",
          "Multimedia",
          "Terminal Systems",
        ],
        "Cleaning": [
          "Floor Cleaning Machines",
          "High Pressure Cleaning Technology",
          "Industrial Cleaning Technology",
          "Cleaning Systems",
          "Cleaning Equipment",
          "Cleaning Machines",
          "Washing Systems",
          "Water Jet Systems",
        ],
        "Vehicles": [
          "Construction Vehicles",
          "Electric Vehicles",
          "Vehicle Manufacturing",
          "Vehicle Supplies",
          "Fire Trucks",
          "Aerospace Industry",
          "Commercial Vehicles",
          "Marine Technology",
          "Snow Vehicles",
          "Special Vehicles",
          "Transport Vehicles",
        ],
        "Climate Technology": [
          "Air Conditioning Systems",
          "Climate Equipment",
          "Refrigeration Machines",
          "Cooling Systems",
          "Coolers",
          "Air Cooling Systems",
          "Ventilation Systems",
        ],
        "Welding": [
          "Manual Welding Technology",
          "Welding Units",
          "Welding Systems",
          "Welding Equipment",
          "Welding Machines",
          "Welding Robots",
        ],
        "Fluid Technology": [
          "Compressed Air Systems",
          "Pneumatic Tools",
          "High Pressure Technology",
          "Hydraulic Systems",
          "Hydraulic Products",
          "Hydraulic Tools",
          "Compressors",
          "Pneumatics",
        ],
        "Laboratory Technology": [
          "Laboratory Systems",
          "Laboratory Refrigerators",
          "Laboratory Machines",
          "Laboratory Measurement Technology",
          "Laboratory Shakers",
          "Laboratory Sterilizers",
          "Laboratory Systems",
          "Laboratory Drying Ovens",
          "Laboratory Centrifuges",
          "Laboratory Furnaces",
        ],
        "Drying Technology": [
          "Industrial Dryers",
          "Drying Ovens",
          "Drying Systems",
          "Drying Equipment",
          "Drying Machines",
        ],
        "Conveyor Technology": [
          "Conveyor Belt Systems",
          "Industrial Trucks",
          "Conveyor Systems",
          "Conveyor Machines",
          "Conveyor Systems",
          "Forklifts",
          "Pallet Trucks",
          "Material Handling Systems",
          "Transport Systems",
          "Conveyor Belts",
          "Vertical Conveyor Technology",
          "Workpiece Conveyor Systems",
        ],
        "Food Technology": [
          "Bakery Systems",
          "Bakery Machines",
          "Butchery Machines",
          "Confectionery Machines",
          "Food Processing Systems",
          "Food Processing Machines",
        ],
        "Tools": [
          "Power Tools",
          "Milling Cutters",
          "Hand Tools",
          "Body Shop Tools",
          "Core Drilling Technology",
          "Production Tools",
          "Grinding Tools",
          "Cutting Tools",
          "Special Tool Technology",
          "Clamping Tools",
          "Processing Tools",
          "Tools",
          "Machining Tools",
        ],
        "Gas Technology": [
          "Gas Pressure Regulation Systems",
          "Gas Equipment",
          "Gas Management Systems",
          "Gas Purification Systems",
          "Gas Storage",
          "Micro Gas Generator",
        ],
        "Logistics": [
          "Loading Systems",
          "Unloading Technology",
          "Order Picking Technology",
          "Storage Technology",
          "Transport Equipment",
          "Transport Security",
          "Transport Carts",
          "Loading Technology",
        ],
        "Machine Tools": [
          "Shearing Machines",
          "Band Saw Machines",
          "Construction Saws",
          "Bending Machines",
          "Sheet Metal Processing Machines",
          "Drilling Machines",
          "CNC Machining Centers",
          "CNC Bed Milling Machines",
          "CNC Bending Machines",
          "CNC Lathes",
          "CNC Milling Machines",
          "CNC Machines",
          "Lathes",
          "Turning Technology",
          "Electric Saws",
          "EDM Machines",
          "Milling Machines",
          "Granulators",
          "Planing Machines",
          "Honing Machines",
          "Circular Saws",
          "Laser Processing Machines",
          "Lapping Machines",
          "Plasma Cutting Machines",
          "Presses",
          "Embossing Machines",
          "Straightening Machines",
          "Broaching Machines",
          "Grinding Equipment",
          "Grinding Machines",
          "Forging Machines",
          "Punching Machines",
          "Sawing Systems",
          "Sawing Machines",
          "Saws",
          "Forming Machines",
          "Rolling Machines",
          "Water Jet Cutting Machines",
          "Machine Tool Manufacturing",
          "Machining Centers",
        ],
        "Foundry Industry": [
          "Foundry Systems",
          "Foundry Machines",
          "Casting Processing",
        ],
        "Mechanical Engineering": [
          "Processing Lines",
          "Processing Machines",
          "Industrial Machines",
          "Laminating Machines",
          "Metal Processing Machines",
          "Assembly Machines",
          "Production Machines",
          "Cutting Machines",
          "Special Machine Manufacturing",
          "Sorting Technology",
        ],
        "Size Reduction Technology": [
          "Crushers",
          "Granulation Technology",
          "Wood Size Reduction",
          "Compacting Machines",
          "Grinding Systems",
          "Mills",
          "Cutting Mills",
          "Shredder Systems",
          "Roll Crushers",
          "Roll Size Reducers",
          "Cement Mills",
          "Choppers",
          "Size Reduction Systems",
          "Size Reduction Machines",
        ],
        "Lifting Technology": [
          "Work Platforms",
          "Grippers",
          "Hall Cranes",
          "Manual Lifting Technology",
          "Lifting Platforms",
          "Lifting Machines",
          "Lifting Systems",
          "Lifting Tables",
          "Lift Transport Carts",
          "Industrial Cranes",
          "Cranes",
          "Crane Accessories",
          "Portal Lifters",
          "Vacuum Lifting Technology",
        ],
        "Mechanical Engineering Components": [
          "Energy Chains",
          "Gripper Components",
          "Industrial Machine Parts",
          "Machine Operating Elements",
          "Machine Components",
          "Machine Protection Systems",
          "Rotary Table Systems",
        ],
        "UX Design": [
          "User Experience Consulting",
          "User Interface",
          "User Interface Concepts",
          "User Interface Implementation",
          "User Research",
          "Multitouch",
          "iPhone",
          "iPad",
          "Reality Based User Interfaces",
          "Cross Platform",
          "HTML5",
          "Service Design",
          "HMIs for Industry",
          "Inspiring UI Solutions",
          "User-Centered Design",
        ],
      };
    } else {
      // Deutsche Branchen (Original - Alle Branchen)
      return {
        Antriebstechnik: [
          "Antriebssysteme",
          "Elektroantriebe",
          "Gleitlagertechnik",
          "Industrieantriebe",
          "Lineartechnik",
          "Maschinenlager",
          "Servotechnik",
        ],
        Holzindustrie: [
          "Forsttechnik",
          "Holzbearbeitungsmaschinen",
          "Spalttechnik",
          "Sägewerk",
        ],
        Medizintechnik: [
          "Beatmungstechnik",
          "Medizinische Gerätetechnik",
          "Medizinische Instrumente",
          "Medizinmessgeräte",
          "Zahnmedizintechnik",
        ],
        Automationstechnik: [
          "Automaten",
          "Automationsgeräte",
          "Automatisierung",
          "Automatisierungskomponenten",
          "Maschinensteuerungen",
          "Positioniersysteme",
          "Produktionsautomatisierung",
          "Steuergerät",
          "Steuerung",
          "Steuerungstechnik",
        ],
        Anlagenbau: [
          "Anlagenbaukomponenten",
          "Anlagentechnik",
          "Fabrikationsanlage",
          "Industrieabsauganlagen",
          "Industrieanlagentechnik",
        ],
        Messtechnik: [
          "Analogmesstechnik",
          "Druckmesstechnik",
          "Elektromesstechnik",
          "Industriemesstechnik",
          "Infrarotmesstechnik",
          "Lasermesstechnik",
          "Messanlagen",
          "Messgeräte",
          "Messmaschinen",
          "Mikromesstechnik",
          "Sensormesstechnik",
        ],
        Drucktechnik: [
          "3D-Druck",
          "Digitaldruck",
          "Drucksysteme",
          "Offsetdruck",
          "Siebdruck",
          "Tampondruck",
          "Textildruck",
          "Thermodruck",
          "Tiefdruck",
          "Transferdruck",
        ],
        Industrieroboter: [
          "Arbeitsroboter",
          "Bestückungsroboter",
          "Handhabungsroboter",
          "Lackierroboter",
          "Linearroboter",
          "Manipulationsroboter",
          "Nanoroboter",
          "Portalroboter",
          "Präzisionsroboter",
          "Roboter",
          "Roboteranlagen",
          "Robotersysteme",
          "Robotertechnik",
          "Schwerlastroboter",
          "Sechsachsroboter",
        ],
        Oberflächentechnik: [
          "Beschichtungsanlagen",
          "Beschichtungsgeräte",
          "Beschichtungsmaschine",
          "Lackieranlagen",
          "Lackiergeräte",
          "Lackiermaschinen",
          "Oberflächenbehandlungsanlagen",
          "Oberflächenreinigung",
          "Polieranlagen",
          "Poliermaschinen",
          "Pulverbeschichtungen",
        ],
        Elektrotechnik: [
          "Anzeigeeinheiten",
          "Elektrogeräte",
          "Industrieelektronik",
          "Steckdose",
          "Stecker",
          "Steckverbinder",
          "Transformatoren",
        ],
        Informationstechnik: [
          "Digitale Medien",
          "Informationselektronik",
          "Informationsleitsysteme",
          "Multimedia",
          "Terminalsysteme",
        ],
        Reinigung: [
          "Bodenreinigungsmaschinen",
          "Hochdruckreinigungstechnik",
          "Industriereinigungstechnik",
          "Reinigungsanlagen",
          "Reinigungsgeräte",
          "Reinigungsmaschinen",
          "Waschanlagen",
          "Wasserstrahlen",
        ],
        Fahrzeuge: [
          "Baufahrzeuge",
          "Elektrofahrzeuge",
          "Fahrzeugbau",
          "Fahrzeugbedarf",
          "Feuerwehrfahrzeuge",
          "Luftfahrtindustrie",
          "Nutzfahrzeuge",
          "Schifffahrttechnik",
          "Schneefahrzeug",
          "Sonderfahrzeuge",
          "Transportfahrzeuge",
        ],
        Klimatechnik: [
          "Klimaanlagen",
          "Klimageräte",
          "Kältemaschinen",
          "Kühlanlagen",
          "Kühler",
          "Luftkühlsysteme",
          "Lüftungsanlagen",
        ],
        Schweissen: [
          "Handschweisstechnik",
          "Schweissaggregate",
          "Schweissanlagen",
          "Schweissgeräte",
          "Schweissmaschinen",
          "Schweissroboter",
        ],
        Fluidtechnik: [
          "Druckluftanlagen",
          "Druckluftwerkzeuge",
          "Hochdrucktechnik",
          "Hydraulikanlagen",
          "Hydraulikprodukte",
          "Hydraulikwerkzeuge",
          "Kompressoren",
          "Pneumatik",
        ],
        Labortechnik: [
          "Laboranlagen",
          "Laborkühlgeräte",
          "Labormaschine",
          "Labormesstechnik",
          "Laborschüttler",
          "Laborsterilisatoren",
          "Laborsysteme",
          "Labortrockenschrank",
          "Laborzentrifugen",
          "Laboröfen",
        ],
        Trocknungstechnik: [
          "Industrietrockner",
          "Trockenöfen",
          "Trocknungsanlagen",
          "Trocknungsgeräte",
          "Trocknungsmaschinen",
        ],
        Fördertechnik: [
          "Fliessbandsysteme",
          "Flurförderzeuge",
          "Förderanlagen",
          "Fördermaschinen",
          "Fördersysteme",
          "Gabelstapler",
          "Hubwagen",
          "Materialfördersysteme",
          "Transportanlage",
          "Transportbänder",
          "Vertikalfördertechnik",
          "Werkstückfördersysteme",
        ],
        Lebensmitteltechnik: [
          "Backanlagen",
          "Bäckereimaschinen",
          "Fleischereimaschinen",
          "Konditoreimaschinen",
          "Lebensmittelanlagen",
          "Lebensmittelmaschine",
        ],
        Werkzeuge: [
          "Elektrowerkzeuge",
          "Fräser",
          "Handwerkzeuge",
          "Karosseriewerkzeuge",
          "Kernbohrtechnik",
          "Produktionswerkzeuge",
          "Schleifwerkzeuge",
          "Schneidwerkzeuge",
          "Sonderwerkzeugtechnik",
          "Spannwerkzeuge",
          "Verarbeitungswerkzeuge",
          "Werkzeuge",
          "Zerspanungswerkzeuge",
        ],
        Gastechnik: [
          "Gasdruckregelanlagen",
          "Gasgeräte",
          "Gasmanagementsysteme",
          "Gasreinigungssysteme",
          "Gasspeicher",
          "Mikrogasgenerator",
        ],
        Logistik: [
          "Beladesystem",
          "Entladetechnik",
          "Kommissioniertechnik",
          "Lagertechnik",
          "Transportgeräte",
          "Transportsicherung",
          "Transportwagen",
          "Verladetechnik",
        ],
        Werkzeugmaschinen: [
          "Abschermaschinen",
          "Bandsägemaschine",
          "Bausägen",
          "Biegemaschinen",
          "Blechbearbeitungsmaschinen",
          "Bohrmaschinen",
          "CNC-Bearbeitungszentren",
          "CNC-Bettfräsmaschinen",
          "CNC-Biegemaschinen",
          "CNC-Drehmaschinen",
          "CNC-Fräsmaschinen",
          "CNC-Maschinen",
          "Drehmaschinen",
          "Drehtechnik",
          "Elektrosägen",
          "Erodiermaschinen",
          "Fräsmaschinen",
          "Granulatoren",
          "Hobelmaschinen",
          "Honmaschinen",
          "Kreissäge",
          "Laserbearbeitungsmaschinen",
          "Läppmaschinen",
          "Plasmaschneidmaschine",
          "Pressen",
          "Prägemaschinen",
          "Richtmaschinen",
          "Räummaschinen",
          "Schleifgeräte",
          "Schleifmaschinen",
          "Schmiedemaschinen",
          "Stanzmaschine",
          "Sägeanlagen",
          "Sägemaschinen",
          "Sägen",
          "Umformmaschinen",
          "Walzmaschine",
          "Wasserstrahlschneidmaschinen",
          "Werkzeugmaschinenbau",
          "Zerspanungsmaschinen",
        ],
        Giessereiindustrie: [
          "Giessereianlagen",
          "Giessereimaschine",
          "Gussbearbeitung",
        ],
        Maschinenbau: [
          "Bearbeitungslinien",
          "Bearbeitungsmaschine",
          "Industriemaschinen",
          "Laminiermaschinen",
          "Metallbearbeitungsmaschinen",
          "Montagemaschinen",
          "Produktionsmaschinen",
          "Schneidemaschinen",
          "Sondermaschinenbau",
          "Sortiertechnik",
        ],
        Zerkleinerungstechnik: [
          "Brecher",
          "Granuliertechnik",
          "Holzzerkleinerung",
          "Kompaktiermaschine",
          "Mahlanlagen",
          "Mühlen",
          "Schneidmühlen",
          "Schreddersysteme",
          "Walzenbrecher",
          "Walzenzerkleinerer",
          "Zementmühle",
          "Zerhacker",
          "Zerkleinerungsanlagen",
          "Zerkleinerungsmaschinen",
        ],
        Hebetechnik: [
          "Arbeitsbühnen",
          "Greifer",
          "Hallenkrane",
          "Handhebetechnik",
          "Hebebühnen",
          "Hebemaschine",
          "Hubanlagen",
          "Hubtische",
          "Hubtransportwagen",
          "Industriekrane",
          "Kran",
          "Kranzubehör",
          "Portalheber",
          "Vakuumhebetechnik",
        ],
        Maschinenbaukomponenten: [
          "Energieführungen",
          "Greiferkomponenten",
          "Industriemaschinenteile",
          "Maschinenbedienteile",
          "Maschinenkomponenten",
          "Maschinenschutzsysteme",
          "Rundtischsystem",
        ],
        "UX Design": [
          "User Experience Consulting",
          "User Interface",
          "User Interface Konzepte",
          "User Interface Implementierung",
          "User Research",
          "Multitouch",
          "iPhone",
          "iPad",
          "Reality Based User Interfaces",
          "Cross Plattform",
          "HTML5",
          "Service Design",
          "HMIs für Industrie",
          "Inspirierende UI Lösungen",
          "User-Centered-Design",
        ],
      };
    }
  };

  const industries = getIndustries();

  return (
    <section 
      ref={containerRef} 
      data-background="light" 
      className="relative min-h-screen w-full"
    >
      <YellowBackgroundTop/>
      <div className="absolute inset-0 overflow-hidden flex items-center justify-center">
        <div className="w-full px-2 md:px-8 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            {Object.entries(industries).map(([industry, items], index) => (
              <div key={index}>
                <button
                  className="w-full py-2 md:py-4 px-6 md:px-6 text-left text-black focus:outline-none flex items-center text-0.5xl md:text-1xl lg:text-2xl"
                  onClick={() => toggleAccordion(index)}
                >
                  {!isMobile && (
                    <span className="mr-2 md:mr-4 text-1xl md:text-2xl lg:text-3xl font-thin">
                      {openIndex === index ? '−' : '+'}
                    </span>
                  )}
                  <span className="font-thind">{industry}</span>
                </button>
                {!isMobile && openIndex === index && (
                  <div className="px-8 md:px-8 py-2 md:py-4">
                    <div className="space-y-1 md:space-y-3">
                      {items.map((item: string | number | bigint | boolean | ReactElement<unknown, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal | Promise<string | number | bigint | boolean | ReactPortal | ReactElement<unknown, string | JSXElementConstructor<any>> | Iterable<ReactNode> | null | undefined> | Iterable<ReactNode> | null | undefined, i: Key | null | undefined) => (
                        <div key={i} className="text-black text-base md:text-xl lg:text-2xl">
                          {item}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}